[tool.poetry]
name = "generative-chatbot"
version = "0.1.0"
description = ""
authors = ["adl212 <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
keras = "^2.4.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
